Create hackbot.json
nooralibutt/nooralibutt.github.io pull request #55
Opened 2023-02-03 15:21 UTC by abid-habib

2023-02-03 20:41 UTC, nooralibutt requested changes

2023-02-03 20:41 UTC, nooralibutt commented on hackbot.json
> +    "Devil hacker": [
Use single words

2023-02-03 20:41 UTC, nooralibutt commented on hackbot.json
> +    " Anonymous ": [
Remove extra spacing

2023-02-06 11:18 UTC, mhanzla80 approved these changes

2023-02-06 12:01 UTC, nooralibutt approved these changes

2023-02-06 12:02 UTC, merged